// Copyright 2026 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

use crate::virtwl::{
    virtwl_ioctl_new, virtwl_ioctl_recv, virtwl_ioctl_send, virtwl_ioctl_txn,
    VIRTWL_SEND_MAX_ALLOCS,
};
use std::fs::{File, OpenOptions};
use std::io;
use std::os::fd::{AsRawFd, FromRawFd, OwnedFd, RawFd};
use std::os::unix::fs::OpenOptionsExt;
use std::path::Path;
use tokio::io::unix::AsyncFd;

const MAX_SEND_SIZE: usize = 4096; // Standard page size or buffer size

pub struct VirtWaylandChannel {
    // The device file descriptor (/dev/wl0)
    dev_file: File,
    // The context file descriptor created via ioctl
    // We wrap it in AsyncFd for polling
    ctx_fd: AsyncFd<OwnedFd>,
}

impl VirtWaylandChannel {
    pub fn new<P: AsRef<Path>>(path: P) -> io::Result<Self> {
        let dev_file = OpenOptions::new()
            .read(true)
            .write(true)
            .custom_flags(libc::O_CLOEXEC)
            .open(path)?;

        // Create context
        let mut new_ctx = crate::virtwl::virtwl_ioctl_new::new_ctx();
        unsafe {
            // virtwl_ioctl_new is generated by ioctl_readwrite! and takes *mut T
            let _ =
                virtwl_ioctl_new(dev_file.as_raw_fd(), &mut new_ctx).map_err(io::Error::from)?;
        }

        let ctx_fd_raw = new_ctx.fd;
        if ctx_fd_raw < 0 {
            return Err(io::Error::other(
                "Invalid fd returned from VIRTWL_IOCTL_NEW_CTX",
            ));
        }

        let ctx_fd = unsafe { OwnedFd::from_raw_fd(ctx_fd_raw) };

        // Set non-blocking on context FD for AsyncFd
        let _ = nix::fcntl::fcntl(
            &ctx_fd,
            nix::fcntl::FcntlArg::F_SETFL(nix::fcntl::OFlag::O_NONBLOCK),
        )
        .map_err(io::Error::from)?;

        Ok(Self {
            dev_file,
            ctx_fd: AsyncFd::new(ctx_fd)?,
        })
    }

    pub fn allocate(&self, size: u32) -> io::Result<(OwnedFd, u32)> {
        let mut new_alloc = crate::virtwl::virtwl_ioctl_new::new_alloc(size);
        unsafe {
            let _ = virtwl_ioctl_new(self.dev_file.as_raw_fd(), &mut new_alloc)
                .map_err(io::Error::from)?;
        }

        let fd = new_alloc.fd;
        if fd < 0 {
            return Err(io::Error::other(
                "Invalid fd returned from VIRTWL_IOCTL_NEW_ALLOC",
            ));
        }

        Ok((unsafe { OwnedFd::from_raw_fd(fd) }, size))
    }

    pub fn create_pipe(&self, read: bool) -> io::Result<OwnedFd> {
        let mut new_pipe = if read {
            crate::virtwl::virtwl_ioctl_new::new_pipe_read()
        } else {
            crate::virtwl::virtwl_ioctl_new::new_pipe_write()
        };

        unsafe {
            let _ = virtwl_ioctl_new(self.dev_file.as_raw_fd(), &mut new_pipe)
                .map_err(io::Error::from)?;
        }

        let fd = new_pipe.fd;
        if fd < 0 {
            return Err(io::Error::other(
                "Invalid fd returned from VIRTWL_IOCTL_NEW_PIPE",
            ));
        }

        Ok(unsafe { OwnedFd::from_raw_fd(fd) })
    }

    pub async fn send(&self, data: &[u8], fds: &[RawFd]) -> io::Result<()> {
        if data.len() > MAX_SEND_SIZE {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "Data size exceeds MAX_SEND_SIZE",
            ));
        }

        if fds.len() > VIRTWL_SEND_MAX_ALLOCS {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "Too many file descriptors to send",
            ));
        }

        let header_size = std::mem::size_of::<virtwl_ioctl_txn>();
        let total_bytes = header_size + data.len();

        // Use Vec<u32> to guarantee 4-byte alignment for virtwl_ioctl_txn
        let mut buf: Vec<u32> = vec![0u32; total_bytes.div_ceil(4)];

        {
            let buf_ptr = buf.as_mut_ptr() as *mut u8;
            let txn = unsafe { &mut *(buf_ptr as *mut virtwl_ioctl_txn) };

            txn.len = data.len() as u32;
            for (i, fd) in fds.iter().enumerate() {
                txn.fds[i] = *fd;
            }
            // Fill remaining FDs with -1
            for i in fds.len()..VIRTWL_SEND_MAX_ALLOCS {
                txn.fds[i] = -1;
            }

            // Copy data after header
            unsafe {
                std::ptr::copy_nonoverlapping(data.as_ptr(), buf_ptr.add(header_size), data.len());
            }
        }

        loop {
            let mut guard = self.ctx_fd.writable().await?;
            let res = guard.try_io(|inner| {
                let buf_ptr = buf.as_mut_ptr() as *mut u8;
                // virtwl_ioctl_send is generated by ioctl_read! and takes *mut virtwl_ioctl_txn
                unsafe {
                    virtwl_ioctl_send(inner.as_raw_fd(), buf_ptr as *mut virtwl_ioctl_txn)
                        .map_err(io::Error::from)
                }
            });

            match res {
                Ok(Ok(_)) => return Ok(()),
                Ok(Err(e)) => return Err(e),
                Err(_would_block) => continue,
            }
        }
    }

    pub async fn recv(&self) -> io::Result<(Vec<u8>, Vec<OwnedFd>)> {
        let header_size = std::mem::size_of::<virtwl_ioctl_txn>();
        let buf_size_bytes = header_size + MAX_SEND_SIZE;

        // Use Vec<u32> to guarantee 4-byte alignment for virtwl_ioctl_txn
        let mut buf: Vec<u32> = vec![0u32; buf_size_bytes.div_ceil(4)];

        loop {
            let mut guard = self.ctx_fd.readable().await?;
            let res = guard.try_io(|inner| {
                let buf_ptr = buf.as_mut_ptr() as *mut u8;
                let txn = unsafe { &mut *(buf_ptr as *mut virtwl_ioctl_txn) };
                txn.len = MAX_SEND_SIZE as u32;
                txn.fds.fill(-1); // Prevent reading uninitialized or previous FDs

                // virtwl_ioctl_recv is generated by ioctl_write_ptr! and takes *const virtwl_ioctl_txn.
                // Even though it takes *const, the kernel WRITES to it (because of _IOW direction quirk).
                // So we pass our mutable buffer cast to const.
                unsafe {
                    virtwl_ioctl_recv(
                        inner.as_raw_fd(),
                        txn as *mut virtwl_ioctl_txn as *const virtwl_ioctl_txn,
                    )
                    .map_err(io::Error::from)
                }
            });

            match res {
                Ok(Ok(_)) => {
                    let buf_ptr = buf.as_mut_ptr() as *mut u8;
                    let txn = unsafe { &*(buf_ptr as *const virtwl_ioctl_txn) };
                    let data_len = txn.len as usize;
                    if data_len > MAX_SEND_SIZE {
                        return Err(io::Error::new(
                            io::ErrorKind::InvalidData,
                            "Received data too large",
                        ));
                    }

                    let data_slice =
                        unsafe { std::slice::from_raw_parts(buf_ptr.add(header_size), data_len) };
                    let data = data_slice.to_vec();

                    let mut fds = Vec::new();
                    for &fd in txn.fds.iter() {
                        if fd >= 0 {
                            fds.push(unsafe { OwnedFd::from_raw_fd(fd) });
                        } else {
                            // FDs are packed; first negative FD indicates the end
                            break;
                        }
                    }

                    return Ok((data, fds));
                }
                Ok(Err(e)) => return Err(e),
                Err(_would_block) => continue,
            }
        }
    }
}
