[package]
name = "sommelier"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.31.1", features = ["socket", "poll", "uio", "fs", "ioctl", "mman"] }
tokio = { version = "1.49.0", features = ["full"] }
libc = "0.2"
gbm = "0.16"
drm = "0.11"
zerocopy = { version = "0.7", features = ["derive"] }
log = "0.4.29"
env_logger = "0.11.9"
clap = { version = "4.5", features = ["derive"] }

[build-dependencies]
wayland_codegen = { path = "../wayland_codegen" }

[[bin]]
name = "sommelier"
path = "src/main.rs"
