/*
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

use crate::protocols::text_input_extension_unstable_v1::zcr_extended_text_input_v1;
use crate::protocols::text_input_extension_unstable_v1::zcr_text_input_extension_v1;
use crate::protocols::text_input_unstable_v1::zwp_text_input_manager_v1;
use crate::protocols::text_input_unstable_v1::zwp_text_input_v1;
use crate::protocols::text_input_unstable_v3::zwp_text_input_manager_v3;
use crate::protocols::text_input_unstable_v3::zwp_text_input_v3;
use crate::state::Context;
use crate::wire::{Action, MessageBuilder};
use super::opcodes::{
    ZWP_TEXT_INPUT_V1_REQ_ACTIVATE, ZWP_TEXT_INPUT_V1_REQ_COMMIT_STATE,
    ZWP_TEXT_INPUT_V1_REQ_DEACTIVATE, ZWP_TEXT_INPUT_V1_REQ_SET_CONTENT_TYPE,
    ZWP_TEXT_INPUT_V1_REQ_SET_CURSOR_RECTANGLE, ZWP_TEXT_INPUT_V1_REQ_SET_SURROUNDING_TEXT,
    ZWP_TEXT_INPUT_V3_EVT_COMMIT_STRING, ZWP_TEXT_INPUT_V3_EVT_DELETE_SURROUNDING_TEXT,
    ZWP_TEXT_INPUT_V3_EVT_DONE, ZWP_TEXT_INPUT_V3_EVT_PREEDIT_STRING,
    ZWP_TEXT_INPUT_MANAGER_V1_REQ_CREATE_TEXT_INPUT,
    ZCR_TEXT_INPUT_EXTENSION_V1_REQ_GET_EXTENDED_TEXT_INPUT,
    ZCR_EXTENDED_TEXT_INPUT_V1_REQ_SET_INPUT_TYPE,
    WL_KEYBOARD_EVT_KEY,
};

/// Fetch-and-increment the per-text-input done serial.
///
/// Each synthesized `zwp_text_input_v3.done` event must carry a monotonically
/// increasing serial so the guest can correlate `commit` requests to the
/// matching server-side batch. Wrapping addition is used: a 32-bit serial
/// wraps after ~4 billion events, which is safe in practice (the guest
/// processes each batch before the counter can wrap on a local socket).
///
/// Returns `0` as a fallback when the text input state is not found. This
/// edge case should never occur in practice (the caller always has a valid
/// `guest_id`), but using a sentinel rather than panicking keeps the proxy
/// resilient against unexpected protocol orderings.
fn next_done_serial(ctx: &mut crate::state::Context, guest_id: u32) -> u32 {
    if let Some(state) = ctx.text_inputs.get_mut(&guest_id) {
        let s = state.done_serial;
        state.done_serial = state.done_serial.wrapping_add(1);
        s
    } else {
        log::warn!(
            "next_done_serial: no text_input state for guest_id={}; sending serial=0",
            guest_id
        );
        0
    }
}

/// Send a synthesized `zwp_text_input_v3.done` event to the guest.
///
/// This is the final event in a v3 transactional batch. All preceding events
/// (preedit_string, commit_string, delete_surrounding_text) within the batch
/// are only applied by the guest once it receives this done event.
fn send_v3_done(ctx: &mut crate::state::Context, guest_id: u32) {
    let serial = next_done_serial(ctx, guest_id);
    let mut builder = MessageBuilder::new();
    builder.write_u32(serial);
    let msg = builder.build_message(guest_id, ZWP_TEXT_INPUT_V3_EVT_DONE);
    ctx.host_to_client_queue.push((msg, Vec::new()));
}

pub struct TextInputManagerV1Handler;
impl zwp_text_input_manager_v1::ZwpTextInputManagerV1Handler for TextInputManagerV1Handler {}

// NOTE: This handler is only active when `emulate_compat_shims` is enabled.
// It translates host zwp_text_input_v1 events to guest zwp_text_input_v3 events.
// It can be removed once all target host compositors natively support
// zwp_text_input_v3.
pub struct TextInputV1Handler;
impl zwp_text_input_v1::ZwpTextInputV1Handler for TextInputV1Handler {
    fn on_preedit_string(
        &mut self,
        ctx: &mut Context,
        // The v1 serial is intentionally discarded. v1 sends a per-event serial
        // with each preedit/commit event. v3 uses a synthetic per-batch monotonic
        // serial generated by send_v3_done(), which increments done_serial on
        // each done event. The two serial spaces are incompatible.
        _serial: u32,
        text: &String,
        // v1 preedit_string includes the text that would be committed if composition
        // finalizes. We discard it: v3 preedit_string does not carry this field, and
        // the commit path (on_commit_string) handles final text separately.
        _commit: &String,
    ) -> Action {
        let host_id = ctx.last_sender_id;
        if let Some(guest_id) = ctx.shadow_table.get_guest_id(host_id) {
            // zwp_text_input_v3 requires transactional updates. Rather than applying
            // changes on receipt of single text events as in v1, v3 caches all intermediate
            // events until a `done` event is received. To satisfy the guest client (e.g. WINE),
            // we send the v3 preedit_string event followed immediately by a synthesized v3 done event.

            // Send v3 preedit_string (opcode 2)
            let mut builder = MessageBuilder::new();
            builder.write_string(text);
            builder.write_i32(0); // cursor_begin
            builder.write_i32(0); // cursor_end
            let msg = builder.build_message(guest_id, ZWP_TEXT_INPUT_V3_EVT_PREEDIT_STRING);
            ctx.host_to_client_queue.push((msg, Vec::new()));

            // Send v3 done to commit the preedit change
            send_v3_done(ctx, guest_id);
        }
        Action::Drop
    }

    fn on_commit_string(&mut self, ctx: &mut Context, _serial: u32, text: &String) -> Action {
        let host_id = ctx.last_sender_id;
        if let Some(guest_id) = ctx.shadow_table.get_guest_id(host_id) {
            // When committing text, we must first clear the active preedit state, then send
            // the committed text, then finalize with a done event. The ordering within the
            // done batch is: preedit_string("") → commit_string(text) → done(serial).
            //
            // Per the zwp_text_input_v3 spec, all events between two `done` events form an
            // atomic batch, so the ordering within the batch should not matter semantically.
            // However, WINE's winewayland.drv processes events sequentially even within a
            // batch: clearing preedit first ensures the composition window is dismissed
            // before the committed text is inserted, preventing visual flicker.

            // Send v3 preedit_string to clear active preedit
            let mut builder = MessageBuilder::new();
            builder.write_string("");
            builder.write_i32(0); // cursor_begin
            builder.write_i32(0); // cursor_end
            let msg = builder.build_message(guest_id, ZWP_TEXT_INPUT_V3_EVT_PREEDIT_STRING);
            ctx.host_to_client_queue.push((msg, Vec::new()));

            // Send v3 commit_string containing the committed text
            let mut builder = MessageBuilder::new();
            builder.write_string(text);
            let msg = builder.build_message(guest_id, ZWP_TEXT_INPUT_V3_EVT_COMMIT_STRING);
            ctx.host_to_client_queue.push((msg, Vec::new()));

            // Send v3 done to commit the entire batch transactionally
            send_v3_done(ctx, guest_id);
        }
        Action::Drop
    }

    fn on_keysym(
        &mut self,
        ctx: &mut Context,
        // See the serial comment on on_preedit_string — same rationale applies.
        _serial: u32,
        _time: u32,
        sym: u32,
        state: u32,
        _modifiers: u32,
    ) -> Action {
        // DESIGN NOTE: IME-generated keysyms intentionally bypass accelerator filtering.
        //
        // This handler converts keysyms from the host IME engine (e.g., Backspace or
        // arrow keys emitted during CJK composition) into synthetic wl_keyboard.key
        // events for the guest. These are NOT physical key presses — they are part of
        // the IME composition flow. Routing them through KeyboardHandler's accelerator
        // filter would incorrectly suppress composition-internal keys that happen to
        // match host shortcuts.

        // Use the shared keysym→evdev keycode table populated by keyboard.rs::on_keymap.
        // This uses the host's actual keymap (not a hardcoded "us" layout), giving
        // correct results for non-US keyboard layouts.
        if let Some(&keycode) = ctx.keysym_to_keycode.get(&sym) {
            // Look up the text input state to find which seat this event belongs to,
            // then find the keyboard for that seat. This avoids non-deterministic
            // HashMap iteration order when multiple keyboards exist.
            let host_id = ctx.last_sender_id;
            let keyboard_id = ctx.shadow_table.get_guest_id(host_id)
                .and_then(|guest_ti_id| ctx.text_inputs.get(&guest_ti_id))
                .and_then(|ti_state| {
                    ctx.keyboard_to_seat.iter()
                        .find(|(_, &seat)| seat == ti_state.guest_seat)
                        .map(|(&kb_id, _)| kb_id)
                })
                .or_else(|| {
                    // Allocation-free fallback: use the keyboard with the lowest ID
                    // for determinism. No Vec allocation or sort needed.
                    ctx.keyboard_to_seat.keys().min().copied()
                });

            if let Some(keyboard_id) = keyboard_id {
                let mut builder = MessageBuilder::new();
                builder.write_u32(0); // serial
                builder.write_u32(0); // time
                builder.write_u32(keycode); // key
                builder.write_u32(state); // state (0: released, 1: pressed)
                let msg = builder.build_message(keyboard_id, WL_KEYBOARD_EVT_KEY);
                ctx.host_to_client_queue.push((msg, Vec::new()));
            }
        } else if sym != 0 {
            log::debug!(
                "on_keysym: no evdev keycode found for keysym 0x{:x} (keymap may not be loaded yet)",
                sym
            );
        }
        Action::Drop
    }

    fn on_enter(&mut self, _ctx: &mut Context, _surface: u32) -> Action {
        Action::Drop
    }

    fn on_leave(&mut self, _ctx: &mut Context) -> Action {
        Action::Drop
    }

    fn on_modifiers_map(&mut self, _ctx: &mut Context, _map: &[u8]) -> Action {
        Action::Drop
    }

    fn on_input_panel_state(&mut self, _ctx: &mut Context, _state: u32) -> Action {
        Action::Drop
    }

    fn on_preedit_styling(
        &mut self,
        _ctx: &mut Context,
        _index: u32,
        _length: u32,
        _style: u32,
    ) -> Action {
        Action::Drop
    }

    fn on_preedit_cursor(&mut self, _ctx: &mut Context, _index: i32) -> Action {
        Action::Drop
    }

    fn on_cursor_position(&mut self, _ctx: &mut Context, _index: i32, _anchor: i32) -> Action {
        Action::Drop
    }

    fn on_delete_surrounding_text(
        &mut self,
        ctx: &mut Context,
        index: i32,
        length: u32,
    ) -> Action {
        let host_id = ctx.last_sender_id;
        if let Some(guest_id) = ctx.shadow_table.get_guest_id(host_id) {
            // Protocol semantic translation (lossy):
            //
            // zwp_text_input_v1 (§delete_surrounding_text): deletion is specified as a
            // byte `index` relative to the cursor and a byte `length`. The deletion range
            // can be at an arbitrary offset from the cursor.
            //
            // zwp_text_input_v3 (§delete_surrounding_text): deletion is specified as
            // `before_length` (bytes before cursor) and `after_length` (bytes after cursor).
            // The range MUST be contiguous and adjacent to the cursor.
            //
            // When the v1 deletion range spans the cursor (index < 0, index+length > 0),
            // the translation is exact. When the range is entirely post-cursor (index > 0),
            // we shift it to start at the cursor — this is a lossy approximation inherent
            // to the v3 protocol's design.
            //
            // When the range is entirely pre-cursor (index < 0, index + length <= 0), we
            // extend the deletion range to the cursor (before_length = -index) to ensure
            // the requested range is fully deleted, at the cost of over-deleting the bytes
            // between the range and the cursor.
            if index > 0 {
                log::warn!(
                    "on_delete_surrounding_text: lossy v1→v3 conversion; \
                     v1 deletion at index={}, length={} is entirely post-cursor. \
                     v3 only supports cursor-adjacent deletions; shifting to cursor position.",
                    index, length
                );
            }

            // Clamp length to i32::MAX to prevent narrowing overflow in the
            // arithmetic below. Deletion lengths > 2GB are pathological but the
            // proxy must not silently misbehave on adversarial wire input.
            let length_i32 = i32::try_from(length).unwrap_or_else(|_| {
                log::warn!(
                    "on_delete_surrounding_text: length {} exceeds i32::MAX, clamping",
                    length
                );
                i32::MAX
            });

            // Safety: negate via i64 to avoid i32::MIN overflow.
            // -i32::MIN == 2147483648 which does not fit in i32, causing a panic
            // in debug builds and silent wrapping in release builds. Using i64
            // for the intermediate value is always safe: i64 can represent
            // the entire u32 range required for before_length.
            let before_length = if index < 0 {
                (-(index as i64)) as u32
            } else {
                0
            };
            let after_length = if index.saturating_add(length_i32) > 0 {
                index.saturating_add(length_i32) as u32
            } else {
                0
            };

            // Send v3 delete_surrounding_text
            let mut builder = MessageBuilder::new();
            builder.write_u32(before_length);
            builder.write_u32(after_length);
            let msg = builder.build_message(guest_id, ZWP_TEXT_INPUT_V3_EVT_DELETE_SURROUNDING_TEXT);
            ctx.host_to_client_queue.push((msg, Vec::new()));

            // Send v3 done to commit the deletion transactionally
            send_v3_done(ctx, guest_id);
        }
        Action::Drop
    }

    fn on_language(&mut self, _ctx: &mut Context, _serial: u32, _language: &String) -> Action {
        Action::Drop
    }

    fn on_text_direction(&mut self, _ctx: &mut Context, _serial: u32, _direction: u32) -> Action {
        Action::Drop
    }
}

pub struct TextInputExtensionV1Handler;
impl zcr_text_input_extension_v1::ZcrTextInputExtensionV1Handler for TextInputExtensionV1Handler {}

pub struct ExtendedTextInputV1Handler;
impl zcr_extended_text_input_v1::ZcrExtendedTextInputV1Handler for ExtendedTextInputV1Handler {
    fn on_set_preedit_region(&mut self, _ctx: &mut Context, _index: i32, _length: u32) -> Action {
        Action::Drop
    }
    fn on_clear_grammar_fragments(&mut self, _ctx: &mut Context, _start: u32, _end: u32) -> Action {
        Action::Drop
    }
    fn on_add_grammar_fragment(
        &mut self,
        _ctx: &mut Context,
        _start: u32,
        _end: u32,
        _suggestion: &String,
    ) -> Action {
        Action::Drop
    }
    fn on_set_autocorrect_range(&mut self, _ctx: &mut Context, _start: u32, _end: u32) -> Action {
        Action::Drop
    }
    fn on_set_virtual_keyboard_occluded_bounds(
        &mut self,
        _ctx: &mut Context,
        _x: i32,
        _y: i32,
        _width: i32,
        _height: i32,
    ) -> Action {
        Action::Drop
    }
    fn on_confirm_preedit(&mut self, _ctx: &mut Context, _selection_behavior: u32) -> Action {
        Action::Drop
    }
}

// NOTE: This handler is only active when `emulate_compat_shims` is enabled.
// It emulates a guest zwp_text_input_manager_v3 object by instantiating host
// zwp_text_input_v1 under the hood. It can be removed once all target host
// compositors natively support zwp_text_input_v3.
pub struct TextInputManagerV3Handler;
impl zwp_text_input_manager_v3::ZwpTextInputManagerV3Handler for TextInputManagerV3Handler {
    fn on_get_text_input(&mut self, ctx: &mut Context, id: u32, seat: u32) -> Action {
        let host_v1_id = ctx.shadow_table.allocate_host_id();
        let host_ext_id = ctx.shadow_table.allocate_host_id();

        if let Some(host_manager_id) = ctx.host_text_input_manager_v1_id {
            let mut builder = MessageBuilder::new();
            builder.write_u32(host_v1_id);
            let full_msg = builder.build_message(host_manager_id, ZWP_TEXT_INPUT_MANAGER_V1_REQ_CREATE_TEXT_INPUT);
            ctx.client_to_host_queue.push((full_msg, Vec::new()));
        }

        if let Some(host_ext_manager_id) = ctx.host_text_input_extension_v1_id {
            let mut builder = MessageBuilder::new();
            builder.write_u32(host_ext_id);
            builder.write_u32(host_v1_id);
            let full_msg = builder.build_message(host_ext_manager_id, ZCR_TEXT_INPUT_EXTENSION_V1_REQ_GET_EXTENDED_TEXT_INPUT);
            ctx.client_to_host_queue.push((full_msg, Vec::new()));
        }

        ctx.shadow_table.map_id(id, host_v1_id);
        ctx.shadow_table
            .track_interface(id, "zwp_text_input_v3".to_string());
        ctx.shadow_table
            .track_host_interface(host_v1_id, "zwp_text_input_v1".to_string());
        ctx.shadow_table
            .track_host_interface(host_ext_id, "zcr_extended_text_input_v1".to_string());

        let active_surface = ctx.active_surface_for_seat.get(&seat).copied();

        ctx.text_inputs.insert(
            id,
            crate::state::TextInputState {
                host_v1_id,
                host_ext_id,
                guest_seat: seat,
                active_surface,
                ..Default::default()
            },
        );

        Action::Drop
    }
}

// NOTE: This handler is only active when `emulate_compat_shims` is enabled.
// It translates guest zwp_text_input_v3 requests to host zwp_text_input_v1 requests.
// It can be removed once all target host compositors natively support
// zwp_text_input_v3.
pub struct TextInputV3Handler;
impl zwp_text_input_v3::ZwpTextInputV3Handler for TextInputV3Handler {
    fn on_enable(&mut self, ctx: &mut Context) -> Action {
        let guest_id = ctx.last_sender_id;
        if let Some(state) = ctx.text_inputs.get_mut(&guest_id) {
            state.enabled = true;
            state.enabled_changed = true;
        }
        Action::Drop
    }

    fn on_disable(&mut self, ctx: &mut Context) -> Action {
        let guest_id = ctx.last_sender_id;
        if let Some(state) = ctx.text_inputs.get_mut(&guest_id) {
            state.enabled = false;
            state.enabled_changed = true;
            // Per the zwp_text_input_v3 spec: "after the text input was disabled
            // [...] the state of the text input is considered void." Clear any
            // pending state so that a subsequent enable+commit cycle doesn't
            // re-send stale content types, surrounding text, or cursor rects.
            state.surrounding_text = None;
            state.content_type_changed = false;
            state.cursor_rect = None;
        }
        Action::Drop
    }

    fn on_set_surrounding_text(
        &mut self,
        ctx: &mut Context,
        text: &String,
        cursor: i32,
        anchor: i32,
    ) -> Action {
        let guest_id = ctx.last_sender_id;
        if let Some(state) = ctx.text_inputs.get_mut(&guest_id) {
            state.surrounding_text = Some((text.clone(), cursor, anchor));
        }
        Action::Drop
    }

    fn on_set_text_change_cause(&mut self, ctx: &mut Context, cause: u32) -> Action {
        let guest_id = ctx.last_sender_id;
        if let Some(state) = ctx.text_inputs.get_mut(&guest_id) {
            state.text_change_cause = cause;
        }
        Action::Drop
    }

    fn on_set_content_type(&mut self, ctx: &mut Context, hint: u32, purpose: u32) -> Action {
        let guest_id = ctx.last_sender_id;
        if let Some(state) = ctx.text_inputs.get_mut(&guest_id) {
            state.content_hint = hint;
            state.content_purpose = purpose;
            state.content_type_changed = true;
        }
        Action::Drop
    }

    fn on_set_cursor_rectangle(
        &mut self,
        ctx: &mut Context,
        x: i32,
        y: i32,
        width: i32,
        height: i32,
    ) -> Action {
        let guest_id = ctx.last_sender_id;
        if let Some(state) = ctx.text_inputs.get_mut(&guest_id) {
            state.cursor_rect = Some((x, y, width, height));
        }
        Action::Drop
    }

    fn on_commit(&mut self, ctx: &mut Context) -> Action {
        // This handler is only reachable when emulate_compat_shims is enabled (the v3
        // manager global is only advertised in that mode). Guard at runtime so that a
        // future code change exposing v3 without shims doesn't silently send v1
        // messages to a host that has no v1 text input bound.
        if !ctx.emulate_compat_shims {
            log::error!(
                "TextInputV3Handler::on_commit called but emulate_compat_shims is disabled; \
                 this is a bug — the v3 manager should not have been advertised"
            );
            return Action::Drop;
        }
        let guest_id = ctx.last_sender_id;

        // BORROW-SPLIT INVARIANT: This block borrows `ctx.text_inputs` mutably
        // while pushing to `ctx.client_to_host_queue` and reading from
        // `ctx.shadow_table`. This is safe because Rust's borrow checker treats
        // struct fields independently — the queues and shadow table are disjoint
        // from `text_inputs`. If these are ever refactored into the same
        // container, this code must be restructured.
        if let Some(state) = ctx.text_inputs.get_mut(&guest_id) {
            let host_v1_id = state.host_v1_id;
            let host_seat = ctx.shadow_table.get_host_id(state.guest_seat).unwrap_or(0);
            let host_surface = state
                .active_surface
                .and_then(|s| ctx.shadow_table.get_host_id(s))
                .unwrap_or(0);

            // Handle activation/deactivation transitions.
            // Under zwp_text_input_v1, IME activation requires both a valid seat and a valid surface
            // focused object. If those mappings are not yet resolved on the host side, we must defer
            // sending the activate request to the host.
            // Once the mappings are successfully resolved and the message is successfully queued,
            // we clear the `enabled_changed` flag to prevent duplicate state synchronization.
            //
            // Note: if the mappings are not yet resolved, `enabled_changed` remains true. The
            // activation will be retried on the next keyboard enter event (see keyboard.rs
            // on_enter), which re-triggers pending text input commits when surface focus is
            // established.
            if state.enabled_changed {
                if state.enabled {
                    if host_seat != 0 && host_surface != 0 {
                        let mut builder = MessageBuilder::new();
                        builder.write_u32(host_seat);
                        builder.write_u32(host_surface);
                        let full_msg = builder.build_message(host_v1_id, ZWP_TEXT_INPUT_V1_REQ_ACTIVATE);
                        ctx.client_to_host_queue.push((full_msg, Vec::new()));
                        state.enabled_changed = false;
                    } else {
                        log::debug!(
                            "on_commit: deferring activation for text_input guest_id={}; \
                             host_seat={}, host_surface={} (not yet resolved)",
                            guest_id, host_seat, host_surface
                        );
                    }
                } else {
                    // Deactivation: requires a valid seat to address the message.
                    // If host_seat is not yet resolved, defer — like activation, this
                    // is an unusual race (deactivate before seat mapping is established).
                    // enabled_changed remains true; a subsequent commit once the seat is
                    // known will send the deactivate. If the seat is destroyed before
                    // that happens, the IME on the host side will be cleaned up anyway
                    // by the compositor when the seat disappears.
                    if host_seat != 0 {
                        let mut builder = MessageBuilder::new();
                        builder.write_u32(host_seat);
                        let full_msg = builder.build_message(host_v1_id, ZWP_TEXT_INPUT_V1_REQ_DEACTIVATE);
                        ctx.client_to_host_queue.push((full_msg, Vec::new()));
                        state.enabled_changed = false;
                    } else {
                        log::debug!(
                            "on_commit: deferring deactivation for text_input guest_id={}; \
                             host_seat not yet resolved",
                            guest_id
                        );
                    }
                }
            }

            if let Some((text, cursor, anchor)) = state.surrounding_text.take() {
                let mut builder = MessageBuilder::new();
                builder.write_string(&text);
                // v3 uses i32 for cursor/anchor; v1 uses u32. Negative values
                // (e.g. "not set" sentinel) wrap to large positive u32 values.
                // This matches the C sommelier reference behavior.
                builder.write_u32(cursor as u32);
                builder.write_u32(anchor as u32);
                let full_msg = builder.build_message(host_v1_id, ZWP_TEXT_INPUT_V1_REQ_SET_SURROUNDING_TEXT);
                ctx.client_to_host_queue.push((full_msg, Vec::new()));
            }

            if state.content_type_changed {
                let mut builder = MessageBuilder::new();
                builder.write_u32(state.content_hint);
                builder.write_u32(state.content_purpose);
                let full_msg = builder.build_message(host_v1_id, ZWP_TEXT_INPUT_V1_REQ_SET_CONTENT_TYPE);
                ctx.client_to_host_queue.push((full_msg, Vec::new()));

                // Map v3 content_purpose to zcr_extended_text_input_v1::set_input_type.
                // v3 purposes (per spec): normal(0), alpha(1), digits(2), number(3),
                // phone(4), url(5), email(6), name(7), password(8), pin(9),
                // date(10), time(11), datetime(12), terminal(13).
                let input_type = match state.content_purpose {
                    0 | 1 | 7 => 1, // TEXT (normal, alpha, name)
                    2 | 3 => 2,     // NUMBER (digits, number)
                    4 => 3,         // TELEPHONE (phone)
                    5 => 4,         // URL
                    6 => 5,         // EMAIL
                    8 => 6,         // PASSWORD
                    9 => 2,         // NUMBER (pin — numeric password)
                    // date(10), time(11), datetime(12), terminal(13) → TEXT
                    _ => 1,
                };

                let input_mode = 0; // default
                let input_flags = 0;
                let learning_mode = 0;
                let inline_composition_support = 0;

                let mut ext_builder = MessageBuilder::new();
                ext_builder.write_u32(input_type);
                ext_builder.write_u32(input_mode);
                ext_builder.write_u32(input_flags);
                ext_builder.write_u32(learning_mode);
                ext_builder.write_u32(inline_composition_support);
                let ext_msg = ext_builder.build_message(state.host_ext_id, ZCR_EXTENDED_TEXT_INPUT_V1_REQ_SET_INPUT_TYPE);
                ctx.client_to_host_queue.push((ext_msg, Vec::new()));

                state.content_type_changed = false;
            }

            if let Some((x, y, w, h)) = state.cursor_rect.take() {
                let mut builder = MessageBuilder::new();
                builder.write_i32(x);
                builder.write_i32(y);
                builder.write_i32(w);
                builder.write_i32(h);
                let full_msg = builder.build_message(host_v1_id, ZWP_TEXT_INPUT_V1_REQ_SET_CURSOR_RECTANGLE);
                ctx.client_to_host_queue.push((full_msg, Vec::new()));
            }

            // Only send commit_state when activation was not deferred. If
            // enabled_changed is still true, the activation wasn't sent yet
            // and commit_state would target an inactive text input object on
            // the host, which is at best a no-op and at worst a protocol error.
            if !state.enabled_changed {
                let mut builder = MessageBuilder::new();
                builder.write_u32(0); // serial
                let full_msg = builder.build_message(host_v1_id, ZWP_TEXT_INPUT_V1_REQ_COMMIT_STATE);
                ctx.client_to_host_queue.push((full_msg, Vec::new()));
            }
        }

        Action::Drop
    }

    fn on_destroy(&mut self, ctx: &mut Context) -> Action {
        let guest_id = ctx.last_sender_id;
        if let Some(state) = ctx.text_inputs.remove(&guest_id) {
            // If the text input was enabled, send deactivate to the host so the
            // compositor releases IME resources.
            if state.enabled {
                if let Some(host_seat) = ctx.shadow_table.get_host_id(state.guest_seat) {
                    let mut builder = MessageBuilder::new();
                    builder.write_u32(host_seat);
                    let msg = builder.build_message(state.host_v1_id, ZWP_TEXT_INPUT_V1_REQ_DEACTIVATE);
                    ctx.client_to_host_queue.push((msg, Vec::new()));

                    // Follow up with commit_state per the v1 protocol pattern.
                    let mut builder = MessageBuilder::new();
                    builder.write_u32(0); // serial
                    let msg = builder.build_message(state.host_v1_id, ZWP_TEXT_INPUT_V1_REQ_COMMIT_STATE);
                    ctx.client_to_host_queue.push((msg, Vec::new()));
                }
            }

            // Clean up active_surface_for_seat: if this was the only text input
            // tracking this seat, remove the stale surface entry. Without this,
            // a new text input created for the same seat could inherit a surface
            // that no longer exists.
            //
            // Only remove if no other text input is tracking the same seat.
            let seat_still_tracked = ctx.text_inputs.values().any(|ti| ti.guest_seat == state.guest_seat);
            if !seat_still_tracked {
                ctx.active_surface_for_seat.remove(&state.guest_seat);
            }

            // Clean up the shadow table entries for both host objects.
            // v1 has no destroy request, so we just forget the mappings.
            // The host compositor will clean up the v1 objects when the
            // connection closes.
            ctx.shadow_table.remove_id(guest_id);
            ctx.shadow_table.remove_host_interface(state.host_ext_id);

            log::debug!("TextInputV3 destroyed: guest_id={}, host_v1_id={}, host_ext_id={}", guest_id, state.host_v1_id, state.host_ext_id);
        }
        // Drop — the guest's v3 destroy is consumed by the shim; there's no
        // corresponding v1 destroy request to forward.
        Action::Drop
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::protocols::text_input_unstable_v1::zwp_text_input_v1::ZwpTextInputV1Handler;
    use crate::protocols::text_input_unstable_v3::zwp_text_input_v3::ZwpTextInputV3Handler;
    use crate::state::Context;

    /// Helper: extract opcode from a wire message at the given index in a queue.
    fn msg_opcode(queue: &[(Vec<u8>, Vec<std::os::unix::io::RawFd>)], idx: usize) -> u16 {
        let word2 = u32::from_ne_bytes(queue[idx].0[4..8].try_into().unwrap());
        (word2 & 0xffff) as u16
    }

    /// Helper: extract sender_id from a wire message.
    fn msg_sender(queue: &[(Vec<u8>, Vec<std::os::unix::io::RawFd>)], idx: usize) -> u32 {
        u32::from_ne_bytes(queue[idx].0[0..4].try_into().unwrap())
    }

    /// Helper: set up a context with a host→guest mapping for text input testing.
    fn setup_v1_ctx() -> (Context, u32, u32) {
        let mut ctx = Context::new_for_test(false, false, vec![]);
        let host_v1_id = 10u32;
        let guest_id = 20u32;
        ctx.shadow_table.map_id(guest_id, host_v1_id);
        (ctx, host_v1_id, guest_id)
    }

    #[test]
    fn on_preedit_string_sends_v3_preedit_and_done() {
        let (mut ctx, host_v1_id, guest_id) = setup_v1_ctx();
        ctx.last_sender_id = host_v1_id;

        let mut handler = TextInputV1Handler;
        let text = "こんにちは".to_string();
        let action = handler.on_preedit_string(&mut ctx, 0, &text, &String::new());
        assert_eq!(action, Action::Drop);

        // Should produce exactly 2 messages: preedit_string (opcode 2) + done (opcode 5)
        assert_eq!(ctx.host_to_client_queue.len(), 2);

        assert_eq!(msg_sender(&ctx.host_to_client_queue, 0), guest_id);
        assert_eq!(msg_opcode(&ctx.host_to_client_queue, 0), 2); // preedit_string

        assert_eq!(msg_sender(&ctx.host_to_client_queue, 1), guest_id);
        assert_eq!(msg_opcode(&ctx.host_to_client_queue, 1), 5); // done
    }

    #[test]
    fn on_commit_string_sends_preedit_clear_then_commit_then_done() {
        let (mut ctx, host_v1_id, guest_id) = setup_v1_ctx();
        ctx.last_sender_id = host_v1_id;

        let mut handler = TextInputV1Handler;
        let text = "確定".to_string();
        let action = handler.on_commit_string(&mut ctx, 0, &text);
        assert_eq!(action, Action::Drop);

        // Should produce 3 messages: preedit_string("") + commit_string + done
        assert_eq!(ctx.host_to_client_queue.len(), 3);

        assert_eq!(msg_opcode(&ctx.host_to_client_queue, 0), 2); // preedit_string (clear)
        assert_eq!(msg_opcode(&ctx.host_to_client_queue, 1), 3); // commit_string
        assert_eq!(msg_opcode(&ctx.host_to_client_queue, 2), 5); // done

        // All messages should target the guest_id
        for i in 0..3 {
            assert_eq!(msg_sender(&ctx.host_to_client_queue, i), guest_id);
        }
    }

    #[test]
    fn on_delete_surrounding_text_negative_index_spanning_cursor() {
        let (mut ctx, host_v1_id, _guest_id) = setup_v1_ctx();
        ctx.last_sender_id = host_v1_id;

        let mut handler = TextInputV1Handler;
        // index=-3, length=5: delete 3 bytes before cursor, 2 bytes after cursor
        let action = handler.on_delete_surrounding_text(&mut ctx, -3, 5);
        assert_eq!(action, Action::Drop);

        assert_eq!(ctx.host_to_client_queue.len(), 2);
        assert_eq!(msg_opcode(&ctx.host_to_client_queue, 0), 4); // delete_surrounding_text
        assert_eq!(msg_opcode(&ctx.host_to_client_queue, 1), 5); // done

        // Parse the v3 delete_surrounding_text payload: before_length, after_length
        let msg = &ctx.host_to_client_queue[0].0;
        let before = u32::from_ne_bytes(msg[8..12].try_into().unwrap());
        let after = u32::from_ne_bytes(msg[12..16].try_into().unwrap());
        assert_eq!(before, 3, "before_length for index=-3");
        assert_eq!(after, 2, "after_length for index=-3,length=5");
    }

    #[test]
    fn on_delete_surrounding_text_entirely_before_cursor() {
        let (mut ctx, host_v1_id, _guest_id) = setup_v1_ctx();
        ctx.last_sender_id = host_v1_id;

        let mut handler = TextInputV1Handler;
        // index=-5, length=3: delete 3 bytes entirely before cursor
        let action = handler.on_delete_surrounding_text(&mut ctx, -5, 3);
        assert_eq!(action, Action::Drop);

        let msg = &ctx.host_to_client_queue[0].0;
        let before = u32::from_ne_bytes(msg[8..12].try_into().unwrap());
        let after = u32::from_ne_bytes(msg[12..16].try_into().unwrap());
        assert_eq!(before, 5);
        assert_eq!(after, 0, "entirely before cursor → after_length=0");
    }

    #[test]
    fn on_delete_surrounding_text_positive_index_lossy() {
        let (mut ctx, host_v1_id, _guest_id) = setup_v1_ctx();
        ctx.last_sender_id = host_v1_id;

        let mut handler = TextInputV1Handler;
        // index=2, length=3: delete 3 bytes starting 2 bytes after cursor (lossy approximation)
        let action = handler.on_delete_surrounding_text(&mut ctx, 2, 3);
        assert_eq!(action, Action::Drop);

        let msg = &ctx.host_to_client_queue[0].0;
        let before = u32::from_ne_bytes(msg[8..12].try_into().unwrap());
        let after = u32::from_ne_bytes(msg[12..16].try_into().unwrap());
        assert_eq!(before, 0, "positive index → before_length=0");
        // Lossy: index(2) + length(3) = 5 bytes shifted to start at cursor
        assert_eq!(after, 5, "lossy: shifted to cursor position");
    }

    #[test]
    fn on_delete_surrounding_text_zero_length() {
        let (mut ctx, host_v1_id, _guest_id) = setup_v1_ctx();
        ctx.last_sender_id = host_v1_id;

        let mut handler = TextInputV1Handler;
        let action = handler.on_delete_surrounding_text(&mut ctx, 0, 0);
        assert_eq!(action, Action::Drop);

        let msg = &ctx.host_to_client_queue[0].0;
        let before = u32::from_ne_bytes(msg[8..12].try_into().unwrap());
        let after = u32::from_ne_bytes(msg[12..16].try_into().unwrap());
        assert_eq!(before, 0);
        assert_eq!(after, 0);
    }

    #[test]
    fn on_delete_surrounding_text_i32_min_index() {
        // Regression: index == i32::MIN previously caused a panic in debug builds
        // when computing `(-index) as u32` because `-i32::MIN` overflows i32.
        // The fix promotes to i64 before negation.
        let (mut ctx, host_v1_id, _guest_id) = setup_v1_ctx();
        ctx.last_sender_id = host_v1_id;

        let mut handler = TextInputV1Handler;
        // i32::MIN = -2147483648. before_length should be 2147483648u32.
        let action = handler.on_delete_surrounding_text(&mut ctx, i32::MIN, 0);
        assert_eq!(action, Action::Drop);

        let msg = &ctx.host_to_client_queue[0].0;
        let before = u32::from_ne_bytes(msg[8..12].try_into().unwrap());
        let after = u32::from_ne_bytes(msg[12..16].try_into().unwrap());
        assert_eq!(before, 2147483648u32, "before_length must not overflow on i32::MIN");
        assert_eq!(after, 0);
    }

    #[test]
    fn on_commit_deferred_activation_with_missing_surface() {
        let mut ctx = Context::new_for_test(false, false, vec![]);

        let guest_text_input_id = 100u32;
        let host_v1_id = 200u32;
        let guest_seat = 5u32;
        let host_seat = 50u32;
        ctx.shadow_table.map_id(guest_seat, host_seat);

        ctx.text_inputs.insert(
            guest_text_input_id,
            crate::state::TextInputState {
                host_v1_id,
                host_ext_id: 201,
                guest_seat,
                // No surface → should defer
                enabled: true,
                enabled_changed: true,
                ..Default::default()
            },
        );

        ctx.last_sender_id = guest_text_input_id;
        let mut handler = TextInputV3Handler;
        let action = handler.on_commit(&mut ctx);
        assert_eq!(action, Action::Drop);

        // enabled_changed should remain true (activation deferred)
        let state = ctx.text_inputs.get(&guest_text_input_id).unwrap();
        assert!(state.enabled_changed, "activation should be deferred when surface is missing");
    }

    #[test]
    fn on_commit_deferred_deactivation_with_missing_seat() {
        // When the guest calls disable() then commit() but host_seat is not yet
        // resolved, enabled_changed must stay true (deactivation deferred) rather
        // than being silently discarded.
        let mut ctx = Context::new_for_test(false, false, vec![]);

        let guest_text_input_id = 100u32;
        let host_v1_id = 200u32;
        let guest_seat = 5u32;
        // Deliberately do NOT map guest_seat → host_seat to simulate unresolved mapping.

        ctx.text_inputs.insert(
            guest_text_input_id,
            crate::state::TextInputState {
                host_v1_id,
                host_ext_id: 201,
                guest_seat,
                // Guest disabled IME
                enabled_changed: true,
                ..Default::default()
            },
        );

        ctx.last_sender_id = guest_text_input_id;
        let mut handler = TextInputV3Handler;
        let action = handler.on_commit(&mut ctx);
        assert_eq!(action, Action::Drop);

        // Deactivation was deferred — enabled_changed must remain true.
        let state = ctx.text_inputs.get(&guest_text_input_id).unwrap();
        assert!(
            state.enabled_changed,
            "deactivation should be deferred when host_seat is not resolved"
        );

        // No deactivate message should have been sent.
        assert!(
            ctx.client_to_host_queue.is_empty(),
            "no deactivate message should be sent when seat is unresolved"
        );
    }

    #[test]
    fn on_commit_successful_activation() {
        let mut ctx = Context::new_for_test(false, false, vec![]);

        let guest_text_input_id = 100u32;
        let host_v1_id = 200u32;
        let guest_seat = 5u32;
        let host_seat = 50u32;
        let guest_surface = 7u32;
        let host_surface = 70u32;
        ctx.shadow_table.map_id(guest_seat, host_seat);
        ctx.shadow_table.map_id(guest_surface, host_surface);

        ctx.text_inputs.insert(
            guest_text_input_id,
            crate::state::TextInputState {
                host_v1_id,
                host_ext_id: 201,
                guest_seat,
                active_surface: Some(guest_surface),
                enabled: true,
                enabled_changed: true,
                ..Default::default()
            },
        );

        ctx.last_sender_id = guest_text_input_id;
        let mut handler = TextInputV3Handler;
        let action = handler.on_commit(&mut ctx);
        assert_eq!(action, Action::Drop);

        // enabled_changed should be cleared (activation succeeded)
        let state = ctx.text_inputs.get(&guest_text_input_id).unwrap();
        assert!(!state.enabled_changed, "activation should have succeeded");

        // Should have sent activate message (opcode 0) to host
        assert!(
            ctx.client_to_host_queue.iter().any(|(msg, _)| {
                let sender = u32::from_ne_bytes(msg[0..4].try_into().unwrap());
                let word2 = u32::from_ne_bytes(msg[4..8].try_into().unwrap());
                let opcode = (word2 & 0xffff) as u16;
                sender == host_v1_id && opcode == ZWP_TEXT_INPUT_V1_REQ_ACTIVATE
            }),
            "activate message should have been sent to host"
        );
    }

    #[test]
    fn done_events_have_monotonic_serial() {
        let (mut ctx, host_v1_id, guest_id) = setup_v1_ctx();
        ctx.text_inputs.insert(
            guest_id,
            crate::state::TextInputState {
                host_v1_id,
                host_ext_id: 201,
                guest_seat: 5,
                enabled: true,
                ..Default::default()
            },
        );

        let mut handler = TextInputV1Handler;

        // First done event
        ctx.last_sender_id = host_v1_id;
        handler.on_preedit_string(&mut ctx, 0, &"a".to_string(), &"".to_string());
        
        // Second done event
        handler.on_preedit_string(&mut ctx, 0, &"ab".to_string(), &"".to_string());

        // We expect:
        // Index 0: preedit_string
        // Index 1: done (serial 0)
        // Index 2: preedit_string
        // Index 3: done (serial 1)
        assert_eq!(ctx.host_to_client_queue.len(), 4);

        let msg1 = &ctx.host_to_client_queue[1].0;
        let opcode1 = u32::from_ne_bytes(msg1[4..8].try_into().unwrap()) & 0xffff;
        let serial1 = u32::from_ne_bytes(msg1[8..12].try_into().unwrap());
        assert_eq!(opcode1, ZWP_TEXT_INPUT_V3_EVT_DONE as u32);
        assert_eq!(serial1, 0);

        let msg3 = &ctx.host_to_client_queue[3].0;
        let opcode3 = u32::from_ne_bytes(msg3[4..8].try_into().unwrap()) & 0xffff;
        let serial3 = u32::from_ne_bytes(msg3[8..12].try_into().unwrap());
        assert_eq!(opcode3, ZWP_TEXT_INPUT_V3_EVT_DONE as u32);
        assert_eq!(serial3, 1);
    }

    // -----------------------------------------------------------------------
    // New tests for code review fixes
    // -----------------------------------------------------------------------

    #[test]
    fn on_destroy_sends_deactivate_and_cleans_up() {
        let mut ctx = Context::new_for_test(false, false, vec![]);

        let guest_text_input_id = 100u32;
        let host_v1_id = 200u32;
        let guest_seat = 5u32;
        let host_seat = 50u32;
        ctx.shadow_table.map_id(guest_seat, host_seat);
        ctx.shadow_table.map_id(guest_text_input_id, host_v1_id);

        ctx.text_inputs.insert(
            guest_text_input_id,
            crate::state::TextInputState {
                host_v1_id,
                host_ext_id: 201,
                guest_seat,
                enabled: true, // enabled → destroy should deactivate
                ..Default::default()
            },
        );

        ctx.last_sender_id = guest_text_input_id;
        let mut handler = TextInputV3Handler;
        let action = handler.on_destroy(&mut ctx);
        assert_eq!(action, Action::Drop);

        // text_inputs entry must be removed
        assert!(
            !ctx.text_inputs.contains_key(&guest_text_input_id),
            "text_inputs entry must be removed on destroy"
        );

        // Deactivate + commit_state should have been sent to the host
        assert_eq!(ctx.client_to_host_queue.len(), 2, "deactivate + commit_state expected");

        let deact_opcode = msg_opcode(&ctx.client_to_host_queue, 0);
        assert_eq!(deact_opcode, ZWP_TEXT_INPUT_V1_REQ_DEACTIVATE);

        let commit_opcode = msg_opcode(&ctx.client_to_host_queue, 1);
        assert_eq!(commit_opcode, ZWP_TEXT_INPUT_V1_REQ_COMMIT_STATE);
    }

    #[test]
    fn on_destroy_without_enabled_skips_deactivate() {
        let mut ctx = Context::new_for_test(false, false, vec![]);

        let guest_text_input_id = 100u32;
        let host_v1_id = 200u32;
        let guest_seat = 5u32;
        ctx.shadow_table.map_id(guest_text_input_id, host_v1_id);

        ctx.text_inputs.insert(
            guest_text_input_id,
            crate::state::TextInputState {
                host_v1_id,
                host_ext_id: 201,
                guest_seat,
                // not enabled → no deactivate needed
                ..Default::default()
            },
        );

        ctx.last_sender_id = guest_text_input_id;
        let mut handler = TextInputV3Handler;
        let action = handler.on_destroy(&mut ctx);
        assert_eq!(action, Action::Drop);

        // No deactivate should be sent
        assert!(
            ctx.client_to_host_queue.is_empty(),
            "no deactivate should be sent when text input was not enabled"
        );

        // Entry must still be removed
        assert!(!ctx.text_inputs.contains_key(&guest_text_input_id));
    }

    /// Regression: on_destroy must clean up the host_ext_id from the shadow
    /// table's host_interfaces map. Without this, every create/destroy cycle
    /// leaks an entry in host_interfaces.
    #[test]
    fn on_destroy_cleans_up_host_ext_id() {
        let mut ctx = Context::new_for_test(false, false, vec![]);

        let guest_text_input_id = 100u32;
        let host_v1_id = 200u32;
        let host_ext_id = 201u32;
        let guest_seat = 5u32;
        ctx.shadow_table.map_id(guest_text_input_id, host_v1_id);
        // Simulate the host_ext_id registration done by on_get_text_input
        ctx.shadow_table
            .track_host_interface(host_ext_id, "zcr_extended_text_input_v1".to_string());

        ctx.text_inputs.insert(
            guest_text_input_id,
            crate::state::TextInputState {
                host_v1_id,
                host_ext_id,
                guest_seat,
                ..Default::default()
            },
        );

        ctx.last_sender_id = guest_text_input_id;
        let mut handler = TextInputV3Handler;
        handler.on_destroy(&mut ctx);

        // host_ext_id must be removed from host_interfaces
        assert!(
            ctx.shadow_table.get_host_interface(host_ext_id).is_none(),
            "host_ext_id must be removed from host_interfaces on destroy"
        );
        // guest→host mapping must also be removed
        assert!(
            ctx.shadow_table.get_host_id(guest_text_input_id).is_none(),
            "guest→host mapping must be removed on destroy"
        );
    }

    #[test]
    fn on_commit_runtime_guard_with_shims_disabled() {
        // When emulate_compat_shims is false, on_commit must return Drop
        // with an error log instead of sending v1 messages.
        let mut ctx = Context::new_for_test_with_shims(false, false, false, vec![]);

        let guest_text_input_id = 100u32;
        ctx.text_inputs.insert(
            guest_text_input_id,
            crate::state::TextInputState {
                host_v1_id: 200,
                host_ext_id: 201,
                guest_seat: 5,
                enabled: true,
                enabled_changed: true,
                ..Default::default()
            },
        );

        ctx.last_sender_id = guest_text_input_id;
        let mut handler = TextInputV3Handler;
        let action = handler.on_commit(&mut ctx);
        assert_eq!(action, Action::Drop, "on_commit must return Drop when shims disabled");

        // No messages should have been sent
        assert!(
            ctx.client_to_host_queue.is_empty(),
            "no host messages should be sent when shims are disabled"
        );
    }

    #[test]
    fn on_keysym_uses_shared_keymap_table() {
        let mut ctx = Context::new_for_test(false, false, vec![]);

        let host_v1_id = 10u32;
        let guest_id = 20u32;
        let keyboard_id = 30u32;
        let guest_seat = 5u32;

        ctx.shadow_table.map_id(guest_id, host_v1_id);
        ctx.keyboard_to_seat.insert(keyboard_id, guest_seat);

        ctx.text_inputs.insert(
            guest_id,
            crate::state::TextInputState {
                host_v1_id,
                host_ext_id: 201,
                guest_seat,
                enabled: true,
                ..Default::default()
            },
        );

        // Populate the shared keysym→keycode table (normally done by keyboard.rs on_keymap)
        // KEY_BackSpace keysym=0xff08, evdev keycode=14
        ctx.keysym_to_keycode.insert(0xff08, 14);

        ctx.last_sender_id = host_v1_id;
        let mut handler = TextInputV1Handler;
        let action = handler.on_keysym(&mut ctx, 0, 0, 0xff08, 1, 0);
        assert_eq!(action, Action::Drop);

        // Should have generated a synthetic wl_keyboard.key event
        assert_eq!(ctx.host_to_client_queue.len(), 1, "one key event expected");

        let (msg, _) = &ctx.host_to_client_queue[0];
        let sender = u32::from_ne_bytes(msg[0..4].try_into().unwrap());
        assert_eq!(sender, keyboard_id, "key event should be sent via the keyboard object");

        // Verify the keycode in the message (offset 16 = serial(4) + time(4) + key(4))
        let keycode = u32::from_ne_bytes(msg[16..20].try_into().unwrap());
        assert_eq!(keycode, 14, "keycode should be evdev BackSpace (14)");
    }

    #[test]
    fn on_keysym_no_event_when_keymap_not_loaded() {
        let mut ctx = Context::new_for_test(false, false, vec![]);
        let host_v1_id = 10u32;
        let guest_id = 20u32;
        ctx.shadow_table.map_id(guest_id, host_v1_id);

        // keysym_to_keycode is empty (no keymap loaded yet)
        ctx.last_sender_id = host_v1_id;
        let mut handler = TextInputV1Handler;
        let action = handler.on_keysym(&mut ctx, 0, 0, 0xff08, 1, 0);
        assert_eq!(action, Action::Drop);

        // No key event should be generated
        assert!(
            ctx.host_to_client_queue.is_empty(),
            "no key event when keysym_to_keycode table is empty"
        );
    }

    #[test]
    fn on_disable_clears_pending_state() {
        // Per the v3 spec, after disable the text input state is "void".
        // Pending content type, surrounding text, and cursor rect should be
        // cleared so a subsequent enable+commit doesn't re-send stale data.
        let mut ctx = Context::new_for_test(false, false, vec![]);

        let guest_text_input_id = 100u32;
        ctx.text_inputs.insert(
            guest_text_input_id,
            crate::state::TextInputState {
                host_v1_id: 200,
                host_ext_id: 201,
                guest_seat: 5,
                enabled: true,
                surrounding_text: Some(("hello".to_string(), 5, 5)),
                content_hint: 3,
                content_purpose: 1,
                content_type_changed: true,
                cursor_rect: Some((10, 20, 30, 40)),
                ..Default::default()
            },
        );

        ctx.last_sender_id = guest_text_input_id;
        let mut handler = TextInputV3Handler;
        let action = handler.on_disable(&mut ctx);
        assert_eq!(action, Action::Drop);

        let state = ctx.text_inputs.get(&guest_text_input_id).unwrap();
        assert!(!state.enabled, "enabled must be false after disable");
        assert!(state.enabled_changed, "enabled_changed must be set");
        assert!(
            state.surrounding_text.is_none(),
            "surrounding_text must be cleared on disable"
        );
        assert!(
            !state.content_type_changed,
            "content_type_changed must be cleared on disable"
        );
        assert!(
            state.cursor_rect.is_none(),
            "cursor_rect must be cleared on disable"
        );
        // content_hint and content_purpose values are preserved (they're just
        // not marked for re-send). This matches the spec: "void" means the
        // compositor should not act on them, not that they must be zeroed.
    }

    #[test]
    fn on_destroy_cleans_active_surface_for_seat() {
        let mut ctx = Context::new_for_test(false, false, vec![]);

        let guest_text_input_id = 100u32;
        let host_v1_id = 200u32;
        let guest_seat = 5u32;
        let guest_surface = 7u32;
        ctx.shadow_table.map_id(guest_text_input_id, host_v1_id);

        // Simulate an active surface mapping for this seat
        ctx.active_surface_for_seat.insert(guest_seat, guest_surface);

        ctx.text_inputs.insert(
            guest_text_input_id,
            crate::state::TextInputState {
                host_v1_id,
                host_ext_id: 201,
                guest_seat,
                active_surface: Some(guest_surface),
                ..Default::default()
            },
        );

        ctx.last_sender_id = guest_text_input_id;
        let mut handler = TextInputV3Handler;
        handler.on_destroy(&mut ctx);

        // active_surface_for_seat must be cleaned up since no other text input
        // tracks this seat.
        assert!(
            !ctx.active_surface_for_seat.contains_key(&guest_seat),
            "active_surface_for_seat must be removed when last text input for seat is destroyed"
        );
    }

    #[test]
    fn on_destroy_preserves_active_surface_if_other_text_input_on_same_seat() {
        let mut ctx = Context::new_for_test(false, false, vec![]);

        let guest_ti_1 = 100u32;
        let guest_ti_2 = 101u32;
        let host_v1_1 = 200u32;
        let host_v1_2 = 201u32;
        let guest_seat = 5u32;
        let guest_surface = 7u32;
        ctx.shadow_table.map_id(guest_ti_1, host_v1_1);
        ctx.shadow_table.map_id(guest_ti_2, host_v1_2);

        ctx.active_surface_for_seat.insert(guest_seat, guest_surface);

        let make_state = |host_v1_id: u32| crate::state::TextInputState {
            host_v1_id,
            host_ext_id: host_v1_id + 1,
            guest_seat,
            active_surface: Some(guest_surface),
            ..Default::default()
        };

        ctx.text_inputs.insert(guest_ti_1, make_state(host_v1_1));
        ctx.text_inputs.insert(guest_ti_2, make_state(host_v1_2));

        // Destroy only the first text input
        ctx.last_sender_id = guest_ti_1;
        let mut handler = TextInputV3Handler;
        handler.on_destroy(&mut ctx);

        // active_surface_for_seat must be preserved because guest_ti_2 still
        // tracks the same seat.
        assert!(
            ctx.active_surface_for_seat.contains_key(&guest_seat),
            "active_surface_for_seat must be preserved when other text inputs still track the seat"
        );
    }

    #[test]
    fn on_commit_forwards_content_type_and_input_type() {
        // Verify the full pipeline: set_content_type → on_commit → host
        // receives set_content_type (opcode 6) + set_input_type (opcode 6 on ext).
        let mut ctx = Context::new_for_test(false, false, vec![]);

        let guest_text_input_id = 100u32;
        let host_v1_id = 200u32;
        let guest_seat = 5u32;
        let host_seat = 50u32;
        let guest_surface = 7u32;
        let host_surface = 70u32;
        ctx.shadow_table.map_id(guest_seat, host_seat);
        ctx.shadow_table.map_id(guest_surface, host_surface);

        ctx.text_inputs.insert(
            guest_text_input_id,
            crate::state::TextInputState {
                host_v1_id,
                host_ext_id: 201,
                guest_seat,
                active_surface: Some(guest_surface),
                ..Default::default()
            },
        );

        // Set content type (purpose=8 = password)
        ctx.last_sender_id = guest_text_input_id;
        let mut handler = TextInputV3Handler;
        handler.on_set_content_type(&mut ctx, 0, 8);

        // Verify state is cached
        let state = ctx.text_inputs.get(&guest_text_input_id).unwrap();
        assert!(state.content_type_changed);
        assert_eq!(state.content_purpose, 8);

        // Now commit — should forward content type to host
        handler.on_commit(&mut ctx);

        // Look for set_content_type (opcode 6) and set_input_type (opcode 6) messages
        let has_content_type = ctx.client_to_host_queue.iter().any(|(msg, _)| {
            let sender = u32::from_ne_bytes(msg[0..4].try_into().unwrap());
            let opcode = (u32::from_ne_bytes(msg[4..8].try_into().unwrap()) & 0xffff) as u16;
            sender == host_v1_id && opcode == ZWP_TEXT_INPUT_V1_REQ_SET_CONTENT_TYPE
        });
        assert!(has_content_type, "set_content_type must be sent to host");

        let has_input_type = ctx.client_to_host_queue.iter().any(|(msg, _)| {
            let sender = u32::from_ne_bytes(msg[0..4].try_into().unwrap());
            let opcode = (u32::from_ne_bytes(msg[4..8].try_into().unwrap()) & 0xffff) as u16;
            sender == 201 && opcode == ZCR_EXTENDED_TEXT_INPUT_V1_REQ_SET_INPUT_TYPE
        });
        assert!(has_input_type, "set_input_type must be sent to host ext object");

        // content_type_changed must be cleared after commit
        let state = ctx.text_inputs.get(&guest_text_input_id).unwrap();
        assert!(
            !state.content_type_changed,
            "content_type_changed must be cleared after commit"
        );
    }
}
