name: Virtwl CI

on:
  push:
    branches: ["virtwl"]
  pull_request:
    branches: ["virtwl"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v6

      - name: Install deps
        run: sudo apt-get update && sudo apt-get -y install libxkbcommon-dev libgbm-dev libdrm-dev libexpat1-dev

      - name: Install aarch64 dependencies
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo dpkg --add-architecture arm64
          sudo sed -i 's/Types: deb/Types: deb\nArchitectures: amd64 i386/' /etc/apt/sources.list.d/ubuntu.sources
          cat <<EOF | sudo tee /etc/apt/sources.list.d/ubuntu-ports.sources
          Types: deb
          Architectures: arm64
          URIs: http://ports.ubuntu.com/ubuntu-ports/
          Suites: $(lsb_release -cs) $(lsb_release -cs)-updates $(lsb_release -cs)-security        
          EOF    Components: main universe restricted multiverse
          rustup target add aarch64-unknown-linux-gnu
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu libxkbcommon-dev:arm64 libgbm-dev:arm64 libdrm-dev:arm64 libexpat1-dev:arm64

      - name: Build
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
        run: cargo build --verbose --target ${{ matrix.target }}

      - name: Run tests (x86_64 only)
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: cargo test --verbose --target ${{ matrix.target }}
